# $FreeBSD$

.include <src.opts.mk>

PACKAGE=lib${LIB}
LIB=	ctf
MAN=

SRCS=	ctf_add.c	\
	ctf_errmsg.c	\
	ctf_model.c	\
	ctf_open.c	\
	ctf_specific.c

INCS=	libctf.h

SHLIB_MAJOR=	1

.include <bsd.lib.mk>
